### ISSUE TITLE
Use main instead of latest?

### ISSUE THREAD

**Issue by gymnae** [ai-dock/stable-diffusion-webui-forge#1]
Hi there, 
thank you for your efforts.
Since the latest is ancient and the main dev is back and killing it with commits, could you adjust your image build action to follow the main branch? Maybe a rebuild every 24hrs is enough, since there's no release tagging at the moment.

Cheers

**Comment by robballantyne** [comment]
@gymnae Yes I can do that, but for now you can set both
```
FORGE_REF=main
AUTO_UPDATE=true
```
You can also use a specific commit hash if you want to pin to a known good version
