### ISSUE TITLE
Possible to turn off cloudflare tunnels?

### ISSUE THREAD

**Issue by gitwittidbit** [ai-dock/stable-diffusion-webui-forge#6]
Hi,

is it possible to turn of cloudflare tunnels? I don't want to use them (but put the container behind a reverse proxy).

Thanks!

**Comment by robballantyne** [comment]
> Hi,
> 
> is it possible to turn of cloudflare tunnels? I don't want to use them (but put the container behind a reverse proxy).
> 
> Thanks!

Yes, set `CF_QUICK_TUNNELS=false`

https://github.com/ai-dock/base-image/wiki/2.0-Environment-Variables

**Comment by gitwittidbit** [comment]
Perfect, thank you!

Is it also possible to turn off the built-in authentication? I do pass "WEB_ENABLE_AUTH=FALSE" as an environment variable but still get redirected to the login page when accessing the sd ui directly...

**Comment by robballantyne** [comment]
Try this with lowercase `false`. It shouldn't make a difference actually, but if it does I will fix

**Comment by gitwittidbit** [comment]
Thank you, that works.
